[build]
builder = "nixpacks"
buildCommand = "cd houses-app/backend && npm install && npm run build"

[deploy]
startCommand = "cd houses-app/backend && npm start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
